language: ruby
rbenv:
  - 2.1.5
env: 
  - RAILS_ENV=test
before_script:
  - mysql -e 'create database railiner_testing;'
script: 
  - bundle exec rake db:schema:load
  - bundle exec rake test
notifications:
  email: false
  slack: jaturken:FhaDtZwDXZh6Vxq3YyYJ6li5
