language: ruby
rbenv:
  - 2.1.5
env: 
  - RAILS_ENV=test
before_script:
  - mysql -e 'create database railiner_testing;'
  # - bundle exec rake db:test:prepare
script: 
  # - rake db:migrate RAILS_ENV=test
  # - "mysql -e 'create database railiner_testing;'"
  - bundle exec rake db:schema:load
  # - bundle exec rake db:test:prepare
  - bundle exec rake test
  # - bundle exec rake spec
# after_failure:
#   - "mysql -e 'show databases;'"
#   - "cat ./config/database.yml"
#   - "echo $RAILS_ENV"
#   - "bundle exec rake --version"