default: &default
  adapter: mysql2 
  username: air
  password: 
  host: 127.0.0.1
  pool: 40

development:
  <<: *default
  database: railiner_development

test:
  <<: *default
  database: railiner_testing

production:
  <<: *default
  database: railiner_production
